### ISSUE TITLE
Upgrade does not work if data_directory is specified in postgresql.conf

### ISSUE THREAD

**Issue by hhorak** [devexp-db/postgresql-setup#30]
See https://bugzilla.redhat.com/show_bug.cgi?id=1935301 for more info.

**Comment by mkulik-rh** [comment]
I added more information in BZ. We should decide if we want to support not default configuration ( changed pgdata by configuration file) or just block it.

**Comment by mkulik-rh** [comment]
Linked PR: https://github.com/devexp-db/postgresql-setup/pull/33
